[workspace]
members = ["crates/core", "crates/cli"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
crossterm = "0.28"
owo-colors = "4.0"
regex = "1.0"
walkdir = "2.0"